CREATE TABLE produit (
    duree INTEGER,
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nb_max INTEGER,
    nb_min INTEGER,
    prix DOUBLE PRECISION NOT NULL,
    stock INTEGER DEFAULT 0 NOT NULL,
    type_produit VARCHAR(20) NOT NULL,
    editeur VARCHAR(255),
    nom VARCHAR(255),
    url_image VARCHAR(255),
    url_regle VARCHAR(255),
    categories VARCHAR(255)
);